import asyncio
import json
import logging
import time

import pybreaker
from pydantic import ValidationError

from app.config import settings
from app.db.session import async_session
from app.models.query_log import QueryLog
from app.schemas.query import (
    ComparativeResponse,
    DegradedResponse,
    DiseaseResponse,
    DrugResponse,
    GeneralResponse,
    QueryRequest,
    QueryResponse,
)
from app.services.cache import cache_get, cache_get_any_version, cache_set
from app.services.circuit_breaker import get_breaker, is_provider_available
from app.services.citation_validator import validate_citations
from app.services.data_fetcher import FetchedData, fetch_data_for_query
from app.services.drug_linker import process_text_nodes
from app.services.json_repair import parse_llm_json
from app.services.llm_factory import create_llm, get_alternative_model, get_provider
from app.services.prompt_engine import build_prompt
from app.services.query_classifier import classify_query
from app.services.safety_checker import check_safety
from app.services.source_router import route_query

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This information is generated by AI for educational and clinical decision support purposes only. "
    "It does not replace professional medical judgment. Always verify with current clinical guidelines "
    "and consult appropriate specialists. Patient-specific factors must be considered."
)

RESPONSE_MODELS = {
    "drug": DrugResponse,
    "disease": DiseaseResponse,
    "comparative": ComparativeResponse,
    "general": GeneralResponse,
}

# Async log queue
_log_queue: asyncio.Queue | None = None
_log_task: asyncio.Task | None = None


async def init_log_queue():
    """Initialize the async logging queue and consumer."""
    global _log_queue, _log_task
    _log_queue = asyncio.Queue(maxsize=settings.log_queue_max_size)
    _log_task = asyncio.create_task(_log_consumer())


async def shutdown_log_queue():
    """Shutdown the async logging queue."""
    global _log_task
    if _log_task:
        _log_task.cancel()
        try:
            await _log_task
        except asyncio.CancelledError:
            pass


async def _log_consumer():
    """Drain the log queue and write to DB."""
    while True:
        try:
            entry = await _log_queue.get()
            await _write_log_entry(entry)
        except asyncio.CancelledError:
            break
        except Exception:
            logger.error("Log consumer error", exc_info=True)


async def _write_log_entry(entry: dict):
    """Write a log entry to DB with retry and file fallback."""
    for attempt in range(settings.log_db_retry_max + 1):
        try:
            async with async_session() as session:
                # Truncate oversized response
                response_json = entry.get("response_json", {})
                response_str = json.dumps(response_json)
                truncated = False
                if len(response_str.encode()) > settings.max_response_jsonb_bytes:
                    response_str = response_str[: settings.truncated_response_bytes]
                    response_json = json.loads(response_str + "}")  # best effort
                    truncated = True

                log = QueryLog(
                    query=entry["query"],
                    query_type=entry["query_type"],
                    model_used=entry["model_used"],
                    response_json=response_json,
                    latency_ms=entry["latency_ms"],
                    cached=entry.get("cached", False),
                    truncated=truncated,
                    user_key_id=entry.get("user_key_id"),
                )
                session.add(log)
                await session.commit()
                return
        except Exception:
            if attempt < settings.log_db_retry_max:
                await asyncio.sleep(settings.log_db_retry_backoff)
            else:
                # File fallback
                logger.error(
                    "DB log write failed after retries, writing to file", exc_info=True
                )
                try:
                    import aiofiles

                    async with aiofiles.open(
                        "/app/logs/query_log_fallback.jsonl", "a"
                    ) as f:
                        await f.write(json.dumps(entry, default=str) + "\n")
                except Exception:
                    # Last resort: structured log
                    logger.error(f"FALLBACK_LOG: {json.dumps(entry, default=str)}")


async def _enqueue_log(entry: dict):
    """Add a log entry to the async queue."""
    if _log_queue is None:
        return
    try:
        _log_queue.put_nowait(entry)
    except asyncio.QueueFull:
        logger.warning("Log queue full, dropping oldest entry")
        try:
            _log_queue.get_nowait()
            _log_queue.put_nowait(entry)
        except Exception:
            pass


async def _call_llm(
    model_id: str, prompt: str, max_tokens: int | None = None
) -> str | None:
    """Call LLM with circuit breaker protection."""
    provider = get_provider(model_id)
    breaker = get_breaker(provider)

    try:
        llm = create_llm(model_id, max_tokens=max_tokens)

        @breaker
        async def _invoke():
            response = await llm.ainvoke(prompt)
            return response.content

        return await _invoke()
    except pybreaker.CircuitBreakerError:
        logger.warning(f"Circuit breaker open for {provider}")
        return None
    except Exception:
        logger.error(f"LLM call failed for {model_id}", exc_info=True)
        return None


_CLAIM_FIELDS = {"loe", "cor", "source", "confidence", "value"}
_VALID_LOE = {"I", "II-1", "II-2", "II-3", "III"}
_VALID_COR = {"I", "IIa", "IIb", "III-no-benefit", "III-harm"}


def _coerce_evidenced_claims(obj: object) -> None:
    """Recursively fill missing/invalid required EvidencedClaim fields with safe defaults."""
    if isinstance(obj, dict):
        if "value" in obj or (_CLAIM_FIELDS & obj.keys()):
            # Looks like an EvidencedClaim — fill missing/invalid required fields
            loe = obj.get("loe") or ""
            if not loe or loe not in _VALID_LOE:
                obj["loe"] = "III"
            cor = obj.get("cor") or ""
            if not cor or cor not in _VALID_COR:
                obj["cor"] = "I"
            if not obj.get("source"):
                obj["source"] = "Clinical guidelines"
            if not obj.get("confidence"):
                obj["confidence"] = "low"
        for v in obj.values():
            _coerce_evidenced_claims(v)
    elif isinstance(obj, list):
        for item in obj:
            _coerce_evidenced_claims(item)


def _validate_response(data: dict, query_type: str) -> tuple[dict | None, list[str]]:
    """Validate response structurally (Pydantic) and semantically."""
    warnings = []
    model_cls = RESPONSE_MODELS.get(query_type)
    if not model_cls:
        return data, ["Unknown query type"]

    # Fill in missing required EvidencedClaim fields before validation
    _coerce_evidenced_claims(data)

    try:
        validated = model_cls.model_validate(data)
        data = validated.model_dump()
    except ValidationError as e:
        logger.warning(f"Pydantic validation failed: {e}")
        return None, [f"Structural validation failed: {str(e)[:200]}"]

    # Semantic validation
    if query_type == "drug":
        if not data.get("drug_name"):
            warnings.append("Missing drug_name in response")
        if not data.get("dosing"):
            warnings.append("No dosing information provided")
        # Check duplicate interactions
        interactions = data.get("interactions", [])
        seen_drugs = set()
        for ix in interactions:
            drug = ix.get("drug", "").lower()
            if drug in seen_drugs:
                warnings.append(f"Duplicate interaction entry: {drug}")
            seen_drugs.add(drug)

    elif query_type == "disease":
        if not data.get("disease_name"):
            warnings.append("Missing disease_name in response")
        treatment = data.get("treatment", {})
        if not treatment.get("first_line"):
            warnings.append("No first-line treatment provided")

    elif query_type == "comparative":
        compared = data.get("entities_compared", [])
        if len(compared) < 2:
            warnings.append("Fewer than 2 entities compared")
        if not data.get("detailed_comparison"):
            warnings.append("No detailed comparison provided")

    return data, warnings


async def process_query(
    request: QueryRequest,
    redis_client=None,
    user_key_id: str | None = None,
) -> QueryResponse:
    """Main RAG pipeline orchestrator."""
    start_time = time.time()

    # Classify
    query_type, confidence = classify_query(request.query, request.query_type)

    # Cache check
    cached_data = await cache_get(
        redis_client, request.query, query_type, request.model_id
    )
    if cached_data:
        latency_ms = int((time.time() - start_time) * 1000)
        cached_data["cached"] = True
        cached_data["latency_ms"] = latency_ms
        response = QueryResponse(**cached_data)
        await _enqueue_log(
            {
                "query": request.query,
                "query_type": query_type,
                "model_used": request.model_id,
                "response_json": cached_data,
                "latency_ms": latency_ms,
                "cached": True,
                "user_key_id": user_key_id,
            }
        )
        return response

    # Circuit breaker check
    provider = get_provider(request.model_id)
    if not is_provider_available(provider):
        # Try cached response (any version)
        any_cached = await cache_get_any_version(
            redis_client, request.query, query_type, request.model_id
        )
        if any_cached:
            latency_ms = int((time.time() - start_time) * 1000)
            return QueryResponse(**any_cached, cached=True, latency_ms=latency_ms)

        # Try alternative provider
        alt_model = get_alternative_model(request.model_id)
        if alt_model and is_provider_available(get_provider(alt_model)):
            request_copy = QueryRequest(
                query=request.query,
                query_type=request.query_type,
                model_id=alt_model,
            )
            return await process_query(request_copy, redis_client, user_key_id)

        # Degraded response
        latency_ms = int((time.time() - start_time) * 1000)
        return QueryResponse(
            query_type=query_type,
            model_used=request.model_id,
            response=DegradedResponse(),
            disclaimer=DISCLAIMER,
            latency_ms=latency_ms,
        )

    # Route and fetch external data
    fetched_data: FetchedData | None = None
    if settings.api_fetch_enabled:
        routing = route_query(request.query, query_type)
        if routing.fetch_enabled:
            try:
                fetched_data = await asyncio.wait_for(
                    fetch_data_for_query(query_type, routing.entities),
                    timeout=settings.api_fetch_timeout_seconds + 1.0,
                )
            except asyncio.TimeoutError:
                logger.warning("API fetch timed out — using generate mode")
                fetched_data = FetchedData(query_type=query_type, fallback_to_llm=True)

    # Model and token budget selection
    # Override only for Anthropic models (OpenRouter users keep their chosen model)
    effective_model = request.model_id
    max_tokens = settings.llm_max_tokens_generate
    if (
        settings.model_routing_enabled
        and fetched_data is not None
        and not fetched_data.fallback_to_llm
        and "/" not in request.model_id  # Anthropic model (no "/" = not OpenRouter)
    ):
        effective_model = routing.preferred_model
        # Disease format mode needs more tokens: classifications, pathophysiology, full treatment
        if query_type == "disease":
            max_tokens = settings.llm_max_tokens_format_disease
        else:
            max_tokens = settings.llm_max_tokens_format
        # Optionally use free OpenRouter model for drug/comparative format steps
        if (
            settings.use_free_model_for_format
            and settings.model_format_free
            and query_type in ("drug", "comparative")
        ):
            effective_model = settings.model_format_free

    prompt_mode = (
        "format" if (fetched_data and not fetched_data.fallback_to_llm) else "generate"
    )
    fetch_latency_ms = fetched_data.total_fetch_time_ms if fetched_data else 0

    # Build prompt (format-mode if API data available, generate-mode otherwise)
    prompt = build_prompt(request.query, query_type, fetched_data)

    # LLM call with retry
    raw_response = await _call_llm(effective_model, prompt, max_tokens=max_tokens)

    if raw_response:
        parsed = parse_llm_json(raw_response)
    else:
        parsed = None

    # Retry once if parse failed
    if parsed is None:
        logger.info("First LLM call failed or unparseable, retrying...")
        await asyncio.sleep(settings.llm_retry_backoff_seconds)
        raw_response = await _call_llm(effective_model, prompt, max_tokens=max_tokens)
        if raw_response:
            parsed = parse_llm_json(raw_response)

    if parsed is None:
        latency_ms = int((time.time() - start_time) * 1000)
        return QueryResponse(
            query_type=query_type,
            model_used=effective_model,
            response=DegradedResponse(
                message="Failed to parse AI response",
                suggestion="Try rephrasing your query or switching models",
            ),
            disclaimer=DISCLAIMER,
            latency_ms=latency_ms,
        )

    # Pydantic + semantic validation
    validated_data, validation_warnings = _validate_response(parsed, query_type)
    if validated_data is None:
        latency_ms = int((time.time() - start_time) * 1000)
        return QueryResponse(
            query_type=query_type,
            model_used=effective_model,
            response=DegradedResponse(
                message="Response validation failed",
                suggestion="Try rephrasing your query",
            ),
            validation_warnings=validation_warnings,
            disclaimer=DISCLAIMER,
            latency_ms=latency_ms,
        )

    # Citation validation
    citation_warnings = validate_citations(validated_data, query_type)
    validation_warnings.extend(citation_warnings)

    # Safety check
    safety_warnings = check_safety(request.query, validated_data, query_type)

    # Drug linker
    text_nodes = process_text_nodes(validated_data, query_type)

    # Build typed response
    model_cls = RESPONSE_MODELS[query_type]
    typed_response = model_cls.model_validate(validated_data)

    latency_ms = int((time.time() - start_time) * 1000)

    response = QueryResponse(
        query_type=query_type,
        model_used=effective_model,
        response=typed_response,
        text_nodes=text_nodes,
        safety_warnings=safety_warnings,
        validation_warnings=validation_warnings,
        disclaimer=DISCLAIMER,
        cached=False,
        truncated=False,
        latency_ms=latency_ms,
    )

    # Cache write
    cache_data = response.model_dump()
    await cache_set(
        redis_client, request.query, query_type, request.model_id, cache_data
    )

    # Async log
    await _enqueue_log(
        {
            "query": request.query,
            "query_type": query_type,
            "model_used": request.model_id,
            "effective_model": effective_model,
            "prompt_mode": prompt_mode,
            "fetch_latency_ms": fetch_latency_ms,
            "response_json": cache_data,
            "latency_ms": latency_ms,
            "cached": False,
            "user_key_id": user_key_id,
        }
    )

    return response
