import type { Metadata } from "next";
import { LegalPage, Section, Callout, Bullets } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service — Iatronix",
  description: "The terms you agree to when using Iatronix, including the clinical disclaimer.",
};

// See the maintainer note in ../privacy/page.tsx — same rules apply.
// [REVIEW] markers need the owner's legal/jurisdictional input before launch.

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="25 July 2026">
      <Callout>
        <strong style={{ color: "var(--text-primary)" }}>Draft pending legal review.</strong> These
        terms describe how Iatronix is intended to be used, but they have not been reviewed by a
        lawyer. Items marked [REVIEW] are still to be confirmed.
      </Callout>

      <Section heading="Not medical advice">
        <p>
          <strong style={{ color: "var(--text-primary)" }}>
            Iatronix is a clinical reference and decision-support tool for qualified healthcare
            professionals. It is not a medical device, it does not practise medicine, and it does
            not provide medical advice, diagnosis or treatment.
          </strong>
        </p>
        <p>
          Every answer is generated by an AI system from retrieved literature and may be incomplete,
          out of date, or wrong. You must independently verify anything you intend to act on against
          the primary sources cited, and you remain fully responsible for all clinical decisions you
          make. Never delay or disregard professional judgement because of something you read here.
        </p>
        <p>
          If you are a patient rather than a clinician, do not use Iatronix to make decisions about
          your own health — speak to a qualified healthcare professional.
        </p>
      </Section>

      <Section heading="Who may use it">
        <p>
          Iatronix is intended for healthcare professionals, students and researchers. You must be
          at least 16 years old and able to enter into a binding agreement. You are responsible for
          keeping your account credentials secure and for all activity under your account.
        </p>
      </Section>

      <Section heading="Acceptable use">
        <Bullets
          items={[
            "Do not enter patient-identifiable information into Iatronix.",
            "Do not use it to provide medical advice directly to patients as though it were a clinician.",
            "Do not attempt to disrupt, overload, reverse-engineer or gain unauthorised access to the service.",
            "Do not scrape or bulk-extract content, or resell access to the service.",
            "Respect the terms of the third-party AI providers and data sources the system relies on.",
          ]}
        />
      </Section>

      <Section heading="Your API keys and costs">
        <p>
          Iatronix is bring-your-own-key: AI generation runs on an API key you supply, and any usage
          charges are billed to you by that provider, not by us. You are responsible for the
          security of your key and for monitoring your own usage. We are not liable for provider
          charges, rate limits or outages.
        </p>
      </Section>

      <Section heading="Availability">
        <p>
          Iatronix is provided on an &quot;as is&quot; and &quot;as available&quot; basis, with no
          warranty of any kind. We may change, suspend or discontinue any part of the service at any
          time. We do not guarantee that it will be uninterrupted, error-free, or that retrieved
          evidence will be complete or current.
        </p>
      </Section>

      <Section heading="Intellectual property">
        <p>
          Medical content retrieved from third-party sources remains the property of those sources
          and is subject to their licences. The Iatronix name, interface and software are owned by
          [REVIEW: legal entity name] and licensed to you for personal professional use only.
        </p>
      </Section>

      <Section heading="Limitation of liability">
        <p>
          To the fullest extent permitted by law, Iatronix and its operator are not liable for any
          indirect, incidental or consequential loss, nor for any clinical outcome arising from your
          use of the service. [REVIEW: confirm the liability cap and whether local consumer or
          healthcare law overrides any of this in your jurisdiction.]
        </p>
      </Section>

      <Section heading="Termination">
        <p>
          You may delete your account at any time. We may suspend or terminate access that breaches
          these terms or risks harm to other users or the service.
        </p>
      </Section>

      <Section heading="Governing law and contact">
        <p>
          These terms are governed by the laws of [REVIEW: jurisdiction]. Questions about them can
          be sent to [REVIEW: contact email].
        </p>
      </Section>
    </LegalPage>
  );
}
